_target_: src.models.segmentation_module.SegmentationLitModule

ignore_index: 255
num_classes: 21

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: segmentation_models_pytorch.Unet
  encoder_name: "resnet34"        # choose encoder, e.g. mobilenet_v2 or efficientnet-b7
  encoder_weights: "imagenet"     # use `imagenet` pre-trained weights for encoder initialization
  in_channels: 3                  # model input channels (1 for gray-scale images, 3 for RGB, etc.)
  classes: 21                     # model output channels (number of classes in your dataset)
