_target_: src.datamodules.pascalvoc_datamodule.PascalVOCDataModule
data_dir: ${paths.data_dir}
batch_size: 8
train_val_test_split: [1000, 464]
num_workers: 8
pin_memory: False

transforms:
  train_transform:
    _target_: albumentations.Compose
    _recursive_: True
    transforms: 
    - _target_: albumentations.PadIfNeeded
      min_height: 400
      min_width: 400
    - _target_: albumentations.ShiftScaleRotate
      shift_limit: 0.2
      scale_limit: 0.2
      rotate_limit: 30
      p: 0.5
    - _target_: albumentations.RandomCrop
      height: 320
      width: 320
    - _target_: albumentations.RGBShift
      r_shift_limit: 15
      g_shift_limit: 15
      b_shift_limit: 15
      p: 0.5
    - _target_: albumentations.RandomBrightnessContrast
      p: 0.5
    - _target_: albumentations.Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    - _target_: albumentations.pytorch.ToTensorV2

  test_transform:
    _target_: albumentations.Compose
    _recursive_: True
    transforms: 
    - _target_: albumentations.PadIfNeeded
      min_height: 400
      min_width: 400
    - _target_: albumentations.CenterCrop
      height: 320
      width: 320
    - _target_: albumentations.Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    - _target_: albumentations.pytorch.ToTensorV2
